/**
 * A new version of the till, offered rather than applied.
 *
 * **The rule this file exists to enforce: never mid-sale.** A service worker
 * with `registerType: 'autoUpdate'` installs a new build and takes over on the
 * next navigation, which at a counter can land between the quote and the
 * tender — the cashier reads out a total computed by one version of the pricing
 * rules and the sale is written by another. That is a customer disputing a
 * receipt, and it is entirely avoidable.
 *
 * So two gates, and both have to open:
 *
 * 1. **The cashier accepts.** An update is a decision somebody makes, not
 *    something that happens to them while they are working.
 * 2. **The cart is empty and no payment is in progress.** Even after accepting,
 *    the reload waits. A cashier who taps Update with six items scanned did not
 *    mean "throw those away".
 *
 * The banner sits in the page rather than over it, like every other notice in
 * the register: a modal here blocks the queue, and CLAUDE.md invariant 10
 * forbids the blocking dialogs outright.
 */

import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { useCart } from '@/features/register/cartContext'
import { readSaleInFlight } from '@/features/register/storage'
import { isTillIdle } from './updateGate'

/**
 * What the registration exposes, narrowed to what this component uses.
 *
 * Declared rather than imported from `virtual:pwa-register`: that module exists
 * only when the PWA plugin has run, so importing its types would make every
 * unit test depend on a build artefact. The shape is small and stable.
 */
interface UpdateRegistration {
  needRefresh: boolean
  update: () => Promise<void>
}

export function UpdatePrompt() {
  const { cart } = useCart()
  const [waiting, setWaiting] = useState(false)
  const [accepted, setAccepted] = useState(false)
  const [registration, setRegistration] = useState<UpdateRegistration | null>(null)

  useEffect(() => {
    let cancelled = false

    void registerServiceWorker((update) => {
      if (!cancelled) {
        setRegistration(update)
        setWaiting(true)
      }
    })

    return () => {
      cancelled = true
    }
  }, [])

  /**
   * The second gate.
   *
   * Re-evaluated on every cart change, so an update accepted during a sale
   * applies the moment the sale finishes rather than being forgotten — which
   * would leave a till running an old build until somebody happened to reload.
   */
  const idle = isTillIdle(cart, readSaleInFlight())

  useEffect(() => {
    if (accepted && idle && registration !== null) {
      void registration.update()
    }
  }, [accepted, idle, registration])

  if (!waiting) {
    return null
  }

  return (
    <div
      role="status"
      data-testid="update-available"
      className="flex flex-wrap items-center gap-3 border-b border-border bg-muted px-4 py-2"
    >
      <p className="flex-1 text-sm text-foreground">
        <span className="font-medium">An update is ready.</span>{' '}
        {accepted
          ? 'It will be applied as soon as this sale is finished.'
          : 'It will be applied when the till is between customers.'}
      </p>

      {accepted ? null : (
        <Button
          size="sm"
          onClick={() => {
            setAccepted(true)
          }}
        >
          Update
        </Button>
      )}

      <Button
        variant="ghost"
        size="sm"
        onClick={() => {
          // Dismissed, not declined: the worker stays waiting and the prompt
          // returns on the next load. A cashier mid-rush should be able to make
          // this go away without deciding anything.
          setWaiting(false)
          setAccepted(false)
        }}
      >
        Not now
      </Button>
    </div>
  )
}

/**
 * Wires up the service worker, if this build has one.
 *
 * The `virtual:pwa-register` module is generated by the PWA plugin, so it is
 * absent in tests and in any build made without it. Imported dynamically and
 * behind a `try` for that reason — a till must not fail to start because an
 * optional module is missing.
 */
async function registerServiceWorker(onNeedRefresh: (update: UpdateRegistration) => void) {
  if (!('serviceWorker' in navigator)) {
    return
  }

  try {
    const { registerSW } = (await import(
      /* @vite-ignore */ 'virtual:pwa-register'
    )) as typeof import('virtual:pwa-register')

    const update = registerSW({
      immediate: true,
      onNeedRefresh() {
        onNeedRefresh({
          needRefresh: true,
          // `registerSW` returns the function that posts SKIP_WAITING and
          // reloads. Calling it is what actually applies the update, and it is
          // reached only through the two gates above.
          update: async () => {
            await update(true)
          },
        })
      },
    })
  } catch {
    // No service worker in this build. The app works, it simply does not cache.
  }
}
