// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pos.Data;

#nullable disable

namespace Pos.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731142326_TenantPrimitives")]
    partial class TenantPrimitives
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pos.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("BusinessDayStartOffset")
                        .HasColumnType("interval")
                        .HasColumnName("business_day_start_offset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("TaxMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tax_mode");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_slug");

                    b.ToTable("tenant", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_currency_code_length", "length(\"currency_code\") <= 3");

                            t.HasCheckConstraint("ck_tenant_name_length", "length(\"name\") <= 200");

                            t.HasCheckConstraint("ck_tenant_slug_format", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_tenant_slug_length", "length(\"slug\") <= 63");

                            t.HasCheckConstraint("ck_tenant_tax_mode_allowed", "\"tax_mode\" IN ('Inclusive', 'Exclusive')");

                            t.HasCheckConstraint("ck_tenant_time_zone_id_length", "length(\"time_zone_id\") <= 64");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
