/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Exchange tenant slug, email and password for a token pair */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AuthResponse']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/pin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start a cashier session from an enrolled till */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['PinLoginRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AuthResponse']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/override': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Manager PIN authorising one privileged action, without swapping the session */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['OverrideRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['OverrideGrantResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Rotate a refresh token */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['RefreshRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AuthResponse']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Revoke the current refresh-token family */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['LogoutRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Current user, granted policies and tenant settings */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['MeResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/registers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Every till in this tenant */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['RegisterSummary'][]
          }
        }
      }
    }
    put?: never
    /** Create a till (not yet enrolled) */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateRegisterRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['RegisterSummary']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/registers/{id}/enroll': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Issue a device token — shown once */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['EnrollmentResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/registers/{id}/revoke': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Invalidate a till's device token */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/employees/pin-eligible': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Names for the PIN screen, from an enrolled till only */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PinEligibleEmployee'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/employees': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Every member of staff at this shop */
    get: {
      parameters: {
        query?: {
          activeOnly?: boolean
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['EmployeeSummary'][]
          }
        }
      }
    }
    put?: never
    /** Add a member of staff */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateEmployeeRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['EmployeeSummary']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/employees/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Change a member of staff's name, role or active status */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateEmployeeRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['EmployeeSummary']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/employees/{id}/deactivate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Withdraw a member of staff's access */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/employees/{id}/set-pin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Set or replace a cashier's PIN */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SetPinRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tax-classes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Every tax class in this tenant */
    get: {
      parameters: {
        query?: {
          cursor?: string
          limit?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CursorPageOfTaxClassResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    put?: never
    /** Create a tax class */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateTaxClassRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TaxClassResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tax-classes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Replace a tax class */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateTaxClassRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TaxClassResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Every category in this tenant */
    get: {
      parameters: {
        query?: {
          cursor?: string
          limit?: number | string
          activeOnly?: boolean
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CursorPageOfCategoryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    put?: never
    /** Create a category */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateCategoryRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CategoryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Replace a category */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateCategoryRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CategoryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories/{id}/deactivate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Hide a category from pickers */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories/{id}/activate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Show a category again */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/products': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search and page the catalog */
    get: {
      parameters: {
        query?: {
          cursor?: string
          limit?: number | string
          q?: string
          categoryId?: string
          activeOnly?: boolean
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CursorPageOfProductResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    put?: never
    /** Create a product */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateProductRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProductResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/products/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** One product */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProductResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    /** Replace a product */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateProductRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProductResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/products/by-barcode/{code}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Scan a barcode */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          code: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['BarcodeLookupResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/products/{id}/barcodes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** A product's codes */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['BarcodeResponse'][]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    /** Add a code to a product */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AddBarcodeRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['BarcodeResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/products/{id}/deactivate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Stop selling a product */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/products/{id}/activate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Sell a product again */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/products/{id}/barcodes/{barcodeId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove a code from a product */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
          barcodeId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stock': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** On-hand levels */
    get: {
      parameters: {
        query?: {
          cursor?: string
          limit?: number | string
          q?: string
          belowReorderPoint?: boolean
          activeOnly?: boolean
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CursorPageOfStockLevelResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stock/{productId}/movements': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The ledger for one product */
    get: {
      parameters: {
        query?: {
          cursor?: string
          limit?: number | string
        }
        header?: never
        path: {
          productId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CursorPageOfStockMovementResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stock/discrepancies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Oversells flagged for review */
    get: {
      parameters: {
        query?: {
          cursor?: string
          limit?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CursorPageOfStockDiscrepancyResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stock/adjustments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Receive, correct or write off stock */
    post: {
      parameters: {
        query?: never
        header: {
          /** @description A client-generated GUID, created before the first attempt and reused on every retry. A replay returns the original status and body with Idempotent-Replay: true. */
          'Idempotency-Key': string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateStockAdjustmentRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['StockAdjustmentResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shifts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Open a shift on a register */
    post: {
      parameters: {
        query?: never
        header: {
          /** @description A client-generated GUID, created before the first attempt and reused on every retry. A replay returns the original status and body with Idempotent-Replay: true. */
          'Idempotency-Key': string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['OpenShiftRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ShiftResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shifts/current': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The open shift for a register, or 404 */
    get: {
      parameters: {
        query?: {
          registerId?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ShiftResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shifts/{id}/close': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Close a shift against a counted drawer */
    post: {
      parameters: {
        query?: never
        header: {
          /** @description A client-generated GUID, created before the first attempt and reused on every retry. A replay returns the original status and body with Idempotent-Replay: true. */
          'Idempotency-Key': string
        }
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CloseShiftRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ShiftResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shifts/{id}/cash-movements': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Record cash into or out of the drawer */
    post: {
      parameters: {
        query?: never
        header: {
          /** @description A client-generated GUID, created before the first attempt and reused on every retry. A replay returns the original status and body with Idempotent-Replay: true. */
          'Idempotency-Key': string
        }
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateCashMovementRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CashMovementResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shifts/{id}/report': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The Z-report for one shift */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ReportResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sales': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Sale history */
    get: {
      parameters: {
        query?: {
          cursor?: string
          limit?: number | string
          registerId?: string
          shiftId?: string
          cashierId?: string
          from?: string
          to?: string
          type?: string
          status?: string
          saleNumber?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CursorPageOfSaleSummaryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    put?: never
    /** Complete a sale */
    post: {
      parameters: {
        query?: never
        header: {
          'X-Override-Authorization'?: string
          /** @description A client-generated GUID, created before the first attempt and reused on every retry. A replay returns the original status and body with Idempotent-Replay: true. */
          'Idempotency-Key': string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateSaleRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SaleResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sales/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** One sale with its lines and tenders */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SaleResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sales/by-client-transaction/{clientTransactionId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The sale a client transaction id produced, if it produced one */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          clientTransactionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SaleResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sales/{id}/receipt': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The receipt payload for a sale, rendered server-side */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ReceiptResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sales/quote': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Price a cart without committing it */
    post: {
      parameters: {
        query?: never
        header?: {
          'X-Override-Authorization'?: string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateSaleRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SaleResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sales/{id}/void': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Void a sale and put its stock back */
    post: {
      parameters: {
        query?: never
        header: {
          /** @description A client-generated GUID, created before the first attempt and reused on every retry. A replay returns the original status and body with Idempotent-Replay: true. */
          'Idempotency-Key': string
        }
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['VoidSaleRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SaleResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sales/{id}/refund': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refund all or part of a sale */
    post: {
      parameters: {
        query?: never
        header: {
          /** @description A client-generated GUID, created before the first attempt and reused on every retry. A replay returns the original status and body with Idempotent-Replay: true. */
          'Idempotency-Key': string
        }
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['RefundSaleRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SaleResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/reports/daily': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The trading day's report */
    get: {
      parameters: {
        query?: {
          date?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ReportResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/reports/margins': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Margin by product over a window. Owner only */
    get: {
      parameters: {
        query?: {
          from?: string
          to?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['MarginReportResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['HttpValidationProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AddBarcodeRequest: {
      code: null | string
      isPrimary: null | boolean
    }
    AuthResponse: {
      accessToken: string
      refreshToken: string
      /** Format: int32 */
      expiresIn: number | string
      user: components['schemas']['AuthUser']
    }
    AuthUser: {
      /** Format: uuid */
      id: string
      displayName: string
      role: null | string
      policies: string[]
    }
    BarcodeLookupResponse: {
      /** Format: uuid */
      barcodeId: string
      code: string
      isPrimary: boolean
      /** Format: uuid */
      productId: string
      sku: string
      name: string
      description: null | string
      /** Format: uuid */
      categoryId: null | string
      /** Format: double */
      unitPrice: number | string
      /** Format: double */
      costPrice: null | number | string
      unit: components['schemas']['Unit']
      isActive: boolean
      trackStock: boolean
      /** Format: uuid */
      taxClassId: string
      taxClassName: string
      /** Format: double */
      taxRate: number | string
    }
    BarcodeResponse: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      productId: string
      code: string
      isPrimary: boolean
      /** Format: date-time */
      createdAt: string
    }
    CashMovementResponse: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      shiftId: string
      type: components['schemas']['CashMovementType']
      /** Format: double */
      amount: number | string
      reason: string
      /** Format: uuid */
      performedBy: string
      /** Format: date-time */
      occurredAt: string
    }
    /** @enum {unknown} */
    CashMovementType: 'Drop' | 'Payout' | 'PettyCash' | 'Correction'
    CategoryResponse: {
      /** Format: uuid */
      id: string
      name: string
      /** Format: uuid */
      parentCategoryId: null | string
      /** Format: int32 */
      sortOrder: number | string
      isActive: boolean
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: null | string
    }
    CloseShiftRequest: {
      /** Format: double */
      countedCash: null | number | string
    }
    CreateCashMovementRequest: {
      type: null | string
      /** Format: double */
      amount: null | number | string
      reason: null | string
    }
    CreateCategoryRequest: {
      name: null | string
      /** Format: uuid */
      parentCategoryId: null | string
      /** Format: int32 */
      sortOrder: null | number | string
    }
    CreateEmployeeRequest: {
      displayName: string
      email: string
      role: string
      password: string
      pin: null | string
    }
    CreateProductRequest: {
      sku: null | string
      name: null | string
      description: null | string
      /** Format: uuid */
      categoryId: null | string
      /** Format: uuid */
      taxClassId: null | string
      /** Format: double */
      unitPrice: null | number | string
      /** Format: double */
      costPrice: null | number | string
      unit: null | string
      trackStock: null | boolean
    }
    CreateRegisterRequest: {
      name: string
    }
    CreateSaleRequest: {
      /** Format: uuid */
      clientTransactionId: null | string
      /** Format: uuid */
      registerId: null | string
      /** Format: uuid */
      shiftId: null | string
      lines: null | components['schemas']['SaleLineRequest'][]
      /** Format: double */
      cartDiscountAmount: null | number | string
      tenders: null | components['schemas']['SaleTenderRequest'][]
    }
    CreateStockAdjustmentRequest: {
      /** Format: uuid */
      productId: null | string
      type: null | string
      /** Format: double */
      quantity: null | number | string
      reason: null | string
    }
    CreateTaxClassRequest: {
      name: null | string
      /** Format: double */
      rate: null | number | string
      isDefault: null | boolean
    }
    CursorPageOfCategoryResponse: {
      items: components['schemas']['CategoryResponse'][]
      nextCursor: null | string
      hasMore: boolean
    }
    CursorPageOfProductResponse: {
      items: components['schemas']['ProductResponse'][]
      nextCursor: null | string
      hasMore: boolean
    }
    CursorPageOfSaleSummaryResponse: {
      items: components['schemas']['SaleSummaryResponse'][]
      nextCursor: null | string
      hasMore: boolean
    }
    CursorPageOfStockDiscrepancyResponse: {
      items: components['schemas']['StockDiscrepancyResponse'][]
      nextCursor: null | string
      hasMore: boolean
    }
    CursorPageOfStockLevelResponse: {
      items: components['schemas']['StockLevelResponse'][]
      nextCursor: null | string
      hasMore: boolean
    }
    CursorPageOfStockMovementResponse: {
      items: components['schemas']['StockMovementResponse'][]
      nextCursor: null | string
      hasMore: boolean
    }
    CursorPageOfTaxClassResponse: {
      items: components['schemas']['TaxClassResponse'][]
      nextCursor: null | string
      hasMore: boolean
    }
    EmployeeSummary: {
      /** Format: uuid */
      id: string
      displayName: string
      email: string
      role: null | string
      isActive: boolean
      hasPin: boolean
      /** Format: date-time */
      lastLoginAt: null | string
    }
    EnrollmentResponse: {
      /** Format: uuid */
      registerId: string
      deviceToken: string
    }
    HttpValidationProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number | string
      detail?: null | string
      instance?: null | string
      errors?: {
        [key: string]: string[]
      }
    }
    LinkedRefundResponse: {
      /** Format: uuid */
      id: string
      /** Format: int64 */
      saleNumber: number | string
      /** Format: double */
      total: number | string
      /** Format: date-time */
      completedAt: string
    }
    LoginRequest: {
      tenantSlug: string
      email: string
      password: string
    }
    LogoutRequest: {
      refreshToken: string
    }
    MarginLineResponse: {
      /** Format: uuid */
      productId: string
      description: string
      /** Format: double */
      quantity: number | string
      /** Format: double */
      revenue: number | string
      /** Format: double */
      cost: null | number | string
      /** Format: double */
      margin: null | number | string
    }
    MarginReportResponse: {
      scope: components['schemas']['ReportScopeResponse']
      currencyCode: string
      /** Format: double */
      revenue: number | string
      /** Format: double */
      cost: null | number | string
      /** Format: double */
      margin: null | number | string
      lines: components['schemas']['MarginLineResponse'][]
    }
    MeResponse: {
      user: components['schemas']['AuthUser']
      tenant: components['schemas']['TenantSettings']
    }
    OpenShiftRequest: {
      /** Format: uuid */
      registerId: null | string
      /** Format: double */
      openingFloat: null | number | string
    }
    OverrideGrantResponse: {
      grant: string
      /** Format: int32 */
      expiresIn: number | string
      /** Format: uuid */
      authorizedById: string
      authorizedByName: string
      policies: string[]
    }
    OverrideRequest: {
      /** Format: uuid */
      userId: string
      pin: string
      policies: string[]
    }
    PinEligibleEmployee: {
      /** Format: uuid */
      id: string
      displayName: string
    }
    PinLoginRequest: {
      /** Format: uuid */
      userId: string
      pin: string
    }
    ProductResponse: {
      /** Format: uuid */
      id: string
      sku: string
      name: string
      description: null | string
      /** Format: uuid */
      categoryId: null | string
      /** Format: uuid */
      taxClassId: string
      /** Format: double */
      unitPrice: number | string
      /** Format: double */
      costPrice: null | number | string
      unit: components['schemas']['Unit']
      isActive: boolean
      trackStock: boolean
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: null | string
    }
    /** @enum {unknown} */
    ReceiptKind: 'Sale' | 'Refund' | 'VoidedSale'
    ReceiptLineResponse: {
      /** Format: int32 */
      lineNumber: number | string
      description: string
      /** Format: double */
      quantity: number | string
      /** Format: double */
      unitPrice: number | string
      /** Format: double */
      taxRate: number | string
      /** Format: double */
      discount: number | string
      /** Format: double */
      lineTotal: number | string
      isPriceOverridden: boolean
    }
    ReceiptResponse: {
      kind: components['schemas']['ReceiptKind']
      shop: components['schemas']['ReceiptShopResponse']
      /** Format: uuid */
      saleId: string
      /** Format: int64 */
      saleNumber: number | string
      /** Format: date-time */
      completedAtLocal: string
      /** Format: date-time */
      issuedAtLocal: string
      timeZoneId: string
      cashierName: string
      registerName: string
      taxMode: components['schemas']['TaxMode']
      /** Format: uuid */
      originalSaleId: null | string
      /** Format: int64 */
      originalSaleNumber: null | number | string
      voidReason: null | string
      refundReason: null | string
      lines: components['schemas']['ReceiptLineResponse'][]
      taxBreakdown: components['schemas']['ReceiptTaxLineResponse'][]
      tenders: components['schemas']['ReceiptTenderResponse'][]
      /** Format: double */
      subtotal: number | string
      /** Format: double */
      discountTotal: number | string
      /** Format: double */
      taxTotal: number | string
      /** Format: double */
      roundingAdjustment: number | string
      /** Format: double */
      total: number | string
      /** Format: double */
      changeGiven: number | string
    }
    ReceiptShopResponse: {
      name: string
      addressLine: null | string
      taxNumber: null | string
      header: null | string
      footer: null | string
      currencyCode: string
    }
    ReceiptTaxLineResponse: {
      /** Format: double */
      rate: number | string
      /** Format: double */
      netAmount: number | string
      /** Format: double */
      taxAmount: number | string
      /** Format: double */
      grossAmount: number | string
    }
    ReceiptTenderResponse: {
      method: components['schemas']['TenderMethod']
      /** Format: double */
      amount: number | string
      /** Format: double */
      changeGiven: null | number | string
    }
    RefreshRequest: {
      refreshToken: string
    }
    RefundLineRequest: {
      /** Format: uuid */
      saleLineId: null | string
      /** Format: double */
      quantity: null | number | string
    }
    RefundSaleRequest: {
      /** Format: uuid */
      clientTransactionId: null | string
      /** Format: uuid */
      registerId: null | string
      /** Format: uuid */
      shiftId: null | string
      reason: null | string
      lines: null | components['schemas']['RefundLineRequest'][]
    }
    RegisterSummary: {
      /** Format: uuid */
      id: string
      name: string
      isActive: boolean
      isEnrolled: boolean
      /** Format: date-time */
      lastSeenAt: null | string
    }
    ReportCashMovementResponse: {
      /** Format: uuid */
      id: string
      type: string
      /** Format: double */
      amount: number | string
      reason: string
      performedBy: string
      /** Format: date-time */
      occurredAt: string
    }
    ReportCashResponse: {
      /** Format: double */
      openingFloat: number | string
      /** Format: double */
      cashSales: number | string
      /** Format: double */
      cashRefunds: number | string
      /** Format: double */
      cashMovements: number | string
      /** Format: double */
      expected: number | string
      /** Format: double */
      counted: null | number | string
      /** Format: double */
      variance: null | number | string
      isProvisional: boolean
      movements: components['schemas']['ReportCashMovementResponse'][]
    }
    ReportResponse: {
      scope: components['schemas']['ReportScopeResponse']
      currencyCode: string
      sales: components['schemas']['ReportSalesResponse']
      taxByRate: components['schemas']['ReportTaxLineResponse'][]
      tenders: components['schemas']['ReportTenderResponse'][]
      cash: components['schemas']['ReportCashResponse']
      shifts: components['schemas']['ReportShiftResponse'][]
      voids: components['schemas']['ReportReversalResponse'][]
      refunds: components['schemas']['ReportReversalResponse'][]
    }
    ReportReversalResponse: {
      /** Format: uuid */
      saleId: string
      /** Format: int64 */
      saleNumber: number | string
      /** Format: double */
      total: number | string
      /** Format: date-time */
      at: string
      actor: string
      reason: null | string
      /** Format: int64 */
      originalSaleNumber: null | number | string
    }
    ReportSalesResponse: {
      /** Format: int32 */
      transactionCount: number | string
      /** Format: double */
      gross: number | string
      /** Format: double */
      discounts: number | string
      /** Format: double */
      net: number | string
      /** Format: double */
      tax: number | string
      /** Format: double */
      rounding: number | string
      /** Format: double */
      total: number | string
      /** Format: double */
      refundTotal: number | string
      /** Format: int32 */
      refundCount: number | string
      /** Format: double */
      averageBasket: number | string
    }
    ReportScopeResponse: {
      kind: string
      /** Format: uuid */
      shiftId: null | string
      /** Format: date */
      date: null | string
      /** Format: date-time */
      fromUtc: string
      /** Format: date-time */
      toUtc: string
      timeZoneId: string
    }
    ReportShiftResponse: {
      /** Format: uuid */
      id: string
      registerName: string
      status: string
      openedBy: string
      /** Format: date-time */
      openedAt: string
      closedBy: null | string
      /** Format: date-time */
      closedAt: null | string
      /** Format: double */
      openingFloat: number | string
      /** Format: double */
      expectedCash: null | number | string
      /** Format: double */
      countedCash: null | number | string
      /** Format: double */
      variance: null | number | string
    }
    ReportTaxLineResponse: {
      /** Format: double */
      rate: number | string
      /** Format: double */
      net: number | string
      /** Format: double */
      tax: number | string
    }
    ReportTenderResponse: {
      method: string
      /** Format: double */
      amount: number | string
      /** Format: double */
      changeGiven: number | string
      /** Format: double */
      net: number | string
    }
    SaleLineRequest: {
      /** Format: uuid */
      productId: null | string
      /** Format: double */
      quantity: null | number | string
      /** Format: double */
      unitPriceOverride: null | number | string
      /** Format: double */
      discountAmount: null | number | string
    }
    SaleLineResponse: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      productId: string
      /** Format: int32 */
      lineNumber: number | string
      description: string
      /** Format: double */
      quantity: number | string
      /** Format: double */
      unitPrice: number | string
      /** Format: double */
      taxRate: number | string
      /** Format: double */
      discountAmount: number | string
      /** Format: double */
      lineSubtotal: number | string
      /** Format: double */
      lineTax: number | string
      /** Format: double */
      lineTotal: number | string
      isPriceOverridden: boolean
    }
    SaleResponse: {
      /** Format: uuid */
      id: null | string
      /** Format: int64 */
      saleNumber: null | number | string
      type: components['schemas']['SaleType']
      status: null | components['schemas']['SaleStatus']
      /** Format: double */
      subtotal: number | string
      /** Format: double */
      discountTotal: number | string
      /** Format: double */
      taxTotal: number | string
      /** Format: double */
      roundingAdjustment: number | string
      /** Format: double */
      total: number | string
      /** Format: double */
      changeGiven: number | string
      /** Format: date-time */
      completedAt: null | string
      lines: components['schemas']['SaleLineResponse'][]
      tenders: components['schemas']['SaleTenderResponse'][]
      /** Format: uuid */
      registerId?: null | string
      /** Format: uuid */
      shiftId?: null | string
      /** Format: uuid */
      cashierId?: null | string
      cashierName?: null | string
      registerName?: null | string
      taxMode?: null | components['schemas']['TaxMode']
      /** Format: uuid */
      originalSaleId?: null | string
      /** Format: int64 */
      originalSaleNumber?: null | number | string
      /** Format: date-time */
      voidedAt?: null | string
      voidedByName?: null | string
      voidReason?: null | string
      refundReason?: null | string
      refunds?: null | components['schemas']['LinkedRefundResponse'][]
    }
    /** @enum {unknown} */
    SaleStatus: 'Completed' | 'Voided'
    SaleSummaryResponse: {
      /** Format: uuid */
      id: string
      /** Format: int64 */
      saleNumber: number | string
      type: components['schemas']['SaleType']
      status: components['schemas']['SaleStatus']
      /** Format: uuid */
      registerId: string
      /** Format: uuid */
      shiftId: string
      /** Format: uuid */
      cashierId: string
      cashierName: string
      registerName: string
      /** Format: uuid */
      originalSaleId: null | string
      /** Format: double */
      total: number | string
      /** Format: date-time */
      completedAt: string
    }
    SaleTenderRequest: {
      method: null | string
      /** Format: double */
      amount: null | number | string
      reference: null | string
    }
    SaleTenderResponse: {
      method: components['schemas']['TenderMethod']
      /** Format: double */
      amount: number | string
      /** Format: double */
      changeGiven: null | number | string
    }
    /** @enum {unknown} */
    SaleType: 'Sale' | 'Refund'
    SetPinRequest: {
      pin: string
    }
    ShiftResponse: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      registerId: string
      status: components['schemas']['ShiftStatus']
      /** Format: uuid */
      openedBy: string
      /** Format: date-time */
      openedAt: string
      /** Format: double */
      openingFloat: number | string
      /** Format: uuid */
      closedBy: null | string
      /** Format: date-time */
      closedAt: null | string
      /** Format: double */
      countedCash: null | number | string
      /** Format: double */
      expectedCash: null | number | string
      /** Format: double */
      variance: null | number | string
    }
    /** @enum {unknown} */
    ShiftStatus: 'Open' | 'Closed'
    StockAdjustmentResponse: {
      movement: components['schemas']['StockMovementResponse']
      /** Format: double */
      onHand: number | string
    }
    StockDiscrepancyResponse: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      productId: string
      /** Format: uuid */
      saleId: string
      /** Format: uuid */
      saleLineId: string
      /** Format: double */
      quantityRequested: number | string
      /** Format: double */
      onHandAfter: number | string
      /** Format: date-time */
      detectedAt: string
    }
    StockLevelResponse: {
      /** Format: uuid */
      id: string
      sku: string
      name: string
      unit: components['schemas']['Unit']
      /** Format: double */
      onHand: number | string
      /** Format: double */
      reorderPoint: null | number | string
      belowReorderPoint: boolean
      isActive: boolean
    }
    StockMovementResponse: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      productId: string
      type: components['schemas']['StockMovementType']
      /** Format: double */
      quantity: number | string
      reason: null | string
      /** Format: uuid */
      saleId: null | string
      /** Format: uuid */
      performedBy: null | string
      /** Format: date-time */
      occurredAt: string
    }
    /** @enum {unknown} */
    StockMovementType: 'Receive' | 'Adjust' | 'Sale' | 'Refund' | 'Waste' | 'Recount'
    TaxClassResponse: {
      /** Format: uuid */
      id: string
      name: string
      /** Format: double */
      rate: number | string
      isDefault: boolean
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: null | string
    }
    /** @enum {unknown} */
    TaxMode: 'Inclusive' | 'Exclusive' | null
    TenantSettings: {
      slug: string
      name: string
      currencyCode: string
      timeZoneId: string
      taxMode: string
    }
    /** @enum {unknown} */
    TenderMethod: 'Cash' | 'External' | 'Card' | 'Voucher'
    /** @enum {unknown} */
    Unit: 'Each' | 'Kilogram' | 'Litre'
    UpdateCategoryRequest: {
      name: null | string
      /** Format: uuid */
      parentCategoryId: null | string
      /** Format: int32 */
      sortOrder: null | number | string
    }
    UpdateEmployeeRequest: {
      displayName: string
      role: string
      isActive: boolean
    }
    UpdateProductRequest: {
      sku: null | string
      name: null | string
      description: null | string
      /** Format: uuid */
      categoryId: null | string
      /** Format: uuid */
      taxClassId: null | string
      /** Format: double */
      unitPrice: null | number | string
      /** Format: double */
      costPrice: null | number | string
      unit: null | string
      trackStock: null | boolean
    }
    UpdateTaxClassRequest: {
      name: null | string
      /** Format: double */
      rate: null | number | string
      isDefault: null | boolean
    }
    VoidSaleRequest: {
      reason: null | string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
