<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pos.Core\Pos.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pos.Data.Tests" />
    <InternalsVisibleTo Include="Pos.Api.Tests" />
  </ItemGroup>

</Project>
